### ISSUE TITLE
imlib2 1.9.0 adds a native jxl loader

### ISSUE THREAD

**Issue by alistair7** [alistair7/imlib2-jxl#3]
This goes some way towards making my loader redundant.
 - The native loader doesn't currently support writing.
 - The native loader ignores the color profile of the input. (All the native loaders do AFAICT.)

If neither of those are deal breakers, there's no longer any need to install imlib2-jxl!

If you still want to use it, be aware that because both loaders compile to `jxl.so`, `make install` will now overwrite the native loader if it exists.

I can change imlib2-jxl's target to `jpegxl.so`, but in any case you _must_ remove or rename the native `jxl.so` in the loaders directory, because imlib2 will always prefer it over any other loader name.  (It's not alphabetical - if imlib2 is built with `BUILD_JXL_LOADER` defined, it always looks specifically for `jxl.so` first.)

**Comment by schrmh** [comment]
Issue about writing support on the imlib2 repo:
https://git.enlightenment.org/old/legacy-imlib2/issues/9

**Comment by alistair7** [comment]
Installation issues addressed in the readme.
